config/routes.rb
Rails.application.routes.draw do
  resources :eventos, path_names: { new: 'novo', edit: 'editar'}
  resources :contas_a_receber, path_names: { new: 'nova', edit: 'editar'}
  resources :contas_a_pagar, path_names: { new: 'nova', edit: 'editar'}
  resources :temas, path_names: { new: 'novo', edit: 'editar'}
  resources :fornecedores, path_names: { new: 'novo', edit: 'editar'}
  resources :categorias, path_names: { new: 'nova', edit: 'editar'}
  resources :clientes, path_names: { new: 'novo', edit: 'editar'}

  get 'estados/:id/cidades' => 'estados#cidades', as: :cidades_do_estado

  get 'contas_a_receber/evento/:id' => 'contas_a_receber#evento', as: :contas_a_receber_do_evento

  root 'eventos#index'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :fornecedores
end

app/models/categoria_fornecedor.rb
class CategoriaFornecedor < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :estado
  belongs_to :cidade

  has_many :eventos, dependent: :destroy
  has_many :contas_a_receber

  validates :nome, :estado, :cidade, presence: :true

end

app/models/conta_a_pagar.rb
class ContaAPagar < ActiveRecord::Base
  belongs_to :fornecedor
end

app/models/conta_a_receber.rb
class ContaAReceber < ActiveRecord::Base
  belongs_to :cliente

  validates :cliente, :vencimento, :valor, presence: :true
end

app/models/conta_pagar.rb
class ContaPagar < ActiveRecord::Base
end

app/models/conta_receber.rb
class ContaReceber < ActiveRecord::Base
end

app/models/dependente_cliente.rb
class DependenteCliente < ActiveRecord::Base
belongs_to :clientes
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :tema
  belongs_to :cliente
  belongs_to :tema

  validates :inicio, :fim, :cliente, :tema, presence: :true

  def valor_a_pagar
    self.entrada - self.desconto
  end
end

def print_strftime_formats(a,cur_date)
    a.each do |format|
        b = "%#{format}"
        output = cur_date.strftime(b)
        puts "t.strftime('#{b}'), => #{output}"
    end
end

a = ('a'..'z').to_a
A = ('A'..'Z').to_a

cur_date = Time.now

app/models/forma_pagamento.rb
class FormaPagamento < ActiveRecord::Base
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  belongs_to :estado
  belongs_to :cidade
  belongs_to :categoria
  has_many :contas_a_pagar
end

app/models/tema.rb
class Tema < ActiveRecord::Base
  has_many :eventos
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
    @cidades = @cliente.try(:estado).try(:cidades)
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente foi cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente foi excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :conjuge, :endereco, :bairro, :cep, :estado_id, :cidade_id, :tresidencial, :tcelular, :cpf, :rg )
    end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  def cidades
    @cidades = Estado.find_by(id: params[:id]).cidades
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    if @evento.save
      redirect_to contas_a_receber_do_evento_path @evento
    else
      render :new
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:inicio, :fim, :cortesia, :consumacao, :itens_avulsos, :num_criancas, :num_adultos, :tema_id, :contrato, :documento, :entrada, :desconto, :forma_pagamento, :obs, :cliente_id)
    end
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_action :set_tema, only: [:show, :edit, :update, :destroy]

  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
  end

  # GET /temas/new
  def new
    @tema = Tema.new
  end

  # GET /temas/1/edit
  def edit
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(tema_params)

    respond_to do |format|
      if @tema.save
        format.html { redirect_to @tema, notice: 'Tema was successfully created.' }
        format.json { render :show, status: :created, location: @tema }
      else
        format.html { render :new }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temas/1
  # PATCH/PUT /temas/1.json
  def update
    respond_to do |format|
      if @tema.update(tema_params)
        format.html { redirect_to @tema, notice: 'Tema was successfully updated.' }
        format.json { render :show, status: :ok, location: @tema }
      else
        format.html { render :edit }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy
    @tema.destroy
    respond_to do |format|
      format.html { redirect_to temas_url, notice: 'Tema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tema
      @tema = Tema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tema_params
      params.require(:tema).permit(:nome, :obs)
    end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/conta_pagars_helper.rb
module ContaPagarsHelper
end

app/helpers/conta_recebers_helper.rb
module ContaRecebersHelper
end

app/helpers/contas_a_pagar_helper.rb
module ContasAPagarHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <fieldset>
    <legend>Cliente</legend>
    <div class="row">
      <div class="small-12 medium-4 columns">
        <%= f.label :cliente_id, 'Nome' %>
        <%= f.collection_select(:cliente_id, Cliente.all, :id, :nome, { prompt: 'Escolha o cliente' }) %>
      </div>
    </div>
  </fieldset>

  <fieldset>
  <legend>Duração</legend>
    <div class="row">
      <div class="small-12 medium-4 columns">
        <%= f.label :inicio, 'Início' %>
        <%= f.text_field :inicio %>
      </div>

      <div class="small-12 medium-4 end columns">
        <%= f.label :fim, 'Fim' %>
        <%= f.text_field :fim %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Quantidade de pessoas</legend>

    <div class="row">
      <div class="small-12 medium-3 columns">
        <%= f.label :num_criancas, 'Crianças' %>
        <%= f.number_field :num_criancas %>
      </div>

      <div class="small-12 medium-3 end columns">
        <%= f.label :num_adultos, 'Adultos' %>
        <%= f.number_field :num_adultos %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Tema</legend>

    <div class="row">
       <div class="small-12 medium-4 columns">
          <%= f.label :tema_id, 'Nome' %>
          <%= f.collection_select(:tema_id, Tema.all, :id, :nome, { prompt: 'Escolha o tema' }) %>
        </div>
      </div>
  </fieldset>

  <fieldset>
    <legend>Contratual</legend>

    <div class="row">
      <div class="small-12 medium-4 columns">
        <%= f.label :consumacao, 'Consumação' %>
        <%= f.text_field :consumacao %>
      </div>

      <div class="small-12 medium-4 end columns">
        <%= f.label :itens_avulsos, 'Itens Avulsos' %>
        <%= f.number_field :itens_avulsos %>
      </div>

     <div class="small-12 columns">
        <%= f.label :cortesia, 'Cortesia?' %>
        <%= f.check_box :cortesia %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Financeiro</legend>

    <div class="row">
      <div class="small-12 medium-4 columns">
        <%= f.label :entrada, 'Entrada' %>
        <%= f.text_field :entrada %>
      </div>

      <div class="small-12 medium-4 columns">
        <%= f.label :desconto, 'Desconto' %>
        <%= f.text_field :desconto %>
      </div>

      <div class="small-12 medium-4 columns">
        <%= f.label :forma_pagamento, 'Forma de pagamento' %>
        <%= f.text_field :forma_pagamento %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Documentação</legend>

    <div class="row">
     <div class="small-12 columns">
        <%= f.label :documento, 'Número do documento' %>
        <%= f.text_field :documento %>
      </div>

      <div class="small-12 columns">
        <%= f.label :contrato, 'Gerar contrato?' %>
        <%= f.check_box :contrato %>
      </div>
    </div>


  <div class="row">
    <div class="small-12 columns">
      <%= f.label :obs %>
      <%= f.text_area :obs %>
    </div>
  </div>

  </fieldset>



  <div>
    <%= f.submit 'Salvar', class: 'button' %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1 class="text-center">Edita Evento</h1>

<%= render 'form' %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Inicio</th>
      <th>Fim</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>

        <td><%= evento.inicio.strftime("%c") %></td>
        <td><%= evento.fim.strftime("%c") %></td>
        <td><%= evento.cliente.nome %></td>
        <td><%= link_to 'Exibir', evento %></td>
        <td><%= link_to 'Editar', edit_evento_path(evento) %></td>
        <td><%= link_to 'Excluir', evento, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Novo evento', new_evento_path, class: 'button', method: :get %>

app/views/eventos/new.html.erb
<h1 class="text-center">Novo Evento</h1>

<%= render 'form' %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @evento.cliente.nome %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @evento.inicio %>
</p>

<p>
  <strong>Fim:</strong>
  <%= @evento.fim %>
</p>

<p>
  <% if @evento.cortesia? %>
  <%= "<strong>Este evento é uma cortesia</strong>".html_safe %>
  <% end %>
</p>

<p>
  <strong>Consumacao:</strong>
  <%= @evento.consumacao %>
</p>

<p>
  <strong>Itens avulsos:</strong>
  <%= @evento.itens_avulsos %>
</p>

<p>
  <strong>Num criancas:</strong>
  <%= @evento.num_criancas %>
</p>

<p>
  <strong>Num adultos:</strong>
  <%= @evento.num_adultos %>
</p>

<p>
  <strong>Tema:</strong>
  <%= @evento.tema_id %>
</p>

<p>
  <strong>Contrato:</strong>
  <%= @evento.contrato %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @evento.documento %>
</p>

<p>
  <strong>Entrada:</strong>
  <%= @evento.entrada %>
</p>

<p>
  <strong>Desconto:</strong>
  <%= @evento.desconto %>
</p>

<p>
  <strong>Forma pagamento:</strong>
  <%= @evento.forma_pagamento %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @evento.obs %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @evento.cliente_id %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/temas/_form.html.erb
<%= form_for(@tema) do |f| %>
  <% if @tema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tema.errors.count, "error") %> prohibited this tema from being saved:</h2>

      <ul>
      <% @tema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Identificação</legend>
      <div class="row">
        <div class="small-12 medium-6 columns">
    <%= f.label :nome, 'Nome' %><br>
    <%= f.text_field :nome %>
  </div>
  </div>


  <div class="row">
  <div class="small-12 medium-6 columns">
    <%= f.label :obs , 'Observação' %><br>
    <%= f.text_area :obs %>
  </div>
  </div>

</fieldset>


  <div>
    <%= f.submit 'Salvar' , class: 'button' %>
  </div>
<% end %>

app/views/temas/edit.html.erb
<h1 class="text-center">Edita tema</h1>

<%= render 'form' %>

app/views/temas/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Temas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temas.each do |tema| %>
      <tr>
        <td><%= tema.nome %></td>
        <td><%= tema.obs %></td>
        <td><%= link_to 'Exibir', tema %></td>
        <td><%= link_to 'Editar', edit_tema_path(tema) %></td>
        <td><%= link_to 'Excluir', tema, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= button_to 'Novo tema', new_tema_path, class: 'button', method: :get %>

app/views/temas/new.html.erb
<h1 class="text-center">Novo Tema</h1>

<%= render 'form' %>

app/views/temas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tema.nome %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @tema.obs %>
</p>

<%= link_to 'Edit', edit_tema_path(@tema) %> |
<%= link_to 'Back', temas_path %>