config/routes.rb
Rails.application.routes.draw do
  resources :eventos, path_names: { new: 'novo', edit: 'editar'}
  resources :contas_a_receber, path_names: { new: 'nova', edit: 'editar'}
  resources :contas_a_pagar, path_names: { new: 'nova', edit: 'editar'}
  resources :temas, path_names: { new: 'novo', edit: 'editar'}
  resources :fornecedores, path_names: { new: 'novo', edit: 'editar'}
  resources :categorias, path_names: { new: 'nova', edit: 'editar'}
  resources :clientes, path_names: { new: 'novo', edit: 'editar'}

  get 'estados/:id/cidades' => 'estados#cidades', as: :cidades_do_estado

  get 'contas_a_receber/evento/:id' => 'contas_a_receber#evento', as: :contas_a_receber_do_evento

  root 'eventos#index'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :fornecedores
end

app/models/categoria_fornecedor.rb
class CategoriaFornecedor < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :estado
  belongs_to :cidade

  has_many :eventos, dependent: :destroy
  has_many :contas_a_receber

  validates :nome, :estado, :cidade, presence: :true

end

app/models/conta_a_pagar.rb
class ContaAPagar < ActiveRecord::Base
  belongs_to :fornecedor
end

app/models/conta_a_receber.rb
class ContaAReceber < ActiveRecord::Base
  belongs_to :cliente

  validates :cliente, :vencimento, :valor, presence: :true
end

app/models/conta_pagar.rb
class ContaPagar < ActiveRecord::Base
end

app/models/conta_receber.rb
class ContaReceber < ActiveRecord::Base
end

app/models/dependente_cliente.rb
class DependenteCliente < ActiveRecord::Base
belongs_to :clientes
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :tema
  belongs_to :cliente
  belongs_to :tema

  validates :inicio, :fim, :cliente, :tema, presence: :true

  def valor_a_pagar
    self.entrada - self.desconto
  end
end

def print_strftime_formats(a,cur_date)
    a.each do |format|
        b = "%#{format}"
        output = cur_date.strftime(b)
        puts "t.strftime('#{b}'), => #{output}"
    end
end

a = ('a'..'z').to_a
A = ('A'..'Z').to_a

cur_date = Time.now

app/models/forma_pagamento.rb
class FormaPagamento < ActiveRecord::Base
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  belongs_to :estado
  belongs_to :cidade
  belongs_to :categoria
  has_many :contas_a_pagar
end

app/models/tema.rb
class Tema < ActiveRecord::Base
  has_many :eventos
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  def cidades
    @cidades = Estado.find_by(id: params[:id]).cidades
  end
end

app/controllers/fornecedores_controller.rb
class FornecedoresController < ApplicationController
  before_action :set_fornecedor, only: [:show, :edit, :update, :destroy]

  # GET /fornecedores
  # GET /fornecedores.json
  def index
    @fornecedores = Fornecedor.all
  end

  # GET /fornecedores/1
  # GET /fornecedores/1.json
  def show
  end

  # GET /fornecedores/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedores/1/edit
  def edit
  end

  # POST /fornecedores
  # POST /fornecedores.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully created.' }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedores/1
  # PATCH/PUT /fornecedores/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedores/1
  # DELETE /fornecedores/1.json
  def destroy
    @fornecedor.destroy
    respond_to do |format|
      format.html { redirect_to fornecedores_url, notice: 'Fornecedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nomefantasia, :razaosocial, :endereco, :bairro, :cep, :estado_id, :cidade_id, :tcomercial, :tcelular, :cnpj, :ie, :email, :im, :site, :categoria_id)
    end
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_action :set_tema, only: [:show, :edit, :update, :destroy]

  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
  end

  # GET /temas/new
  def new
    @tema = Tema.new
  end

  # GET /temas/1/edit
  def edit
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(tema_params)

    respond_to do |format|
      if @tema.save
        format.html { redirect_to @tema, notice: 'Tema was successfully created.' }
        format.json { render :show, status: :created, location: @tema }
      else
        format.html { render :new }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temas/1
  # PATCH/PUT /temas/1.json
  def update
    respond_to do |format|
      if @tema.update(tema_params)
        format.html { redirect_to @tema, notice: 'Tema was successfully updated.' }
        format.json { render :show, status: :ok, location: @tema }
      else
        format.html { render :edit }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy
    @tema.destroy
    respond_to do |format|
      format.html { redirect_to temas_url, notice: 'Tema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tema
      @tema = Tema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tema_params
      params.require(:tema).permit(:nome, :obs)
    end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/conta_pagars_helper.rb
module ContaPagarsHelper
end

app/helpers/conta_recebers_helper.rb
module ContaRecebersHelper
end

app/helpers/contas_a_pagar_helper.rb
module ContasAPagarHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/fornecedores/_form.html.erb
<%= form_for(@fornecedor) do |f| %>
  <% if @fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
      <% @fornecedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>

<legend>Identificação</legend>
<div class="row">
<div class="small-12 medium-6 columns">
<%= f.label :nomefantasia, 'Nome Fantasia' %><br>
<%= f.text_field :nomefantasia %>
</div>

<div class="small-12 medium-6 columns">
<%= f.label :razaosocial, 'Razão Social' %><br>
<%= f.text_field :razaosocial %>
</div>

<div class="small-12 medium-6 columns">
<%= f.label :im, 'Inscrição Municipal' %><br>
<%= f.text_field :im %>
</div>

<div class="small-12 medium-6 columns">
<%= f.label :cnpj, 'CNPJ' %><br>
<%= f.text_field :cnpj, class: "fornecedor_cnpj" %>
</div>

<div class="small-12 medium-6 columns">
<%= f.label :ie, 'Inscrição Estadual' %><br>
<%= f.text_field :ie %>
</div>

<div class="small-12 medium-6 columns">
<%= f.label :categoria_id, 'Categoria' %><br>
<%= f.number_field :categoria_id %>
</div>
</div>
</fieldset>

<fieldset>
<legend>Endereço</legend>
<div class="row">
<div class="small-12 medium-6 columns">
<%= f.label :endereco, 'Endereço' %><br>
<%= f.text_field :endereco %>
</div>

<div class="small-12 medium-3 columns">
<%= f.label :bairro, 'Bairro' %><br>
<%= f.text_field :bairro %>
</div>
<div class="small-12 medium-3 columns">
<%= f.label :cep, 'CEP' %><br>
<%= f.text_field :cep, class: "fornecedor_cep" %>
</div>

<div class="small-4 medium-2 columns">
<%= f.label :estado, "Estado" %><br>
<%= f.collection_select :estado, Estado.all, :id, :nome, { prompt: true }%>
</div>

<div class="small-8 medium-5 end columns">
<%= f.label :cidade, 'Cidade' %><br>
<% if @fornecedor.estado.nil? %>
<%= raw('<select id="fornecedor_cidade" name="fornecedor[cidade]"></select') %>
<% else %>
<%= f.collection_select :cidade, @fornecedor.estado.try(:cidade), :id, :nome %>
<% end %>
</div>
</div>
</fieldset>


 <fieldset>
      <legend>Contato</legend>
        <div class="row">
        <div class="small-12 medium-3 columns">
    <%= f.label :tcomercial, "Telefone Comercial" %><br>
    <%= f.text_field :tcomercial, class: "fornecedor_tcomercial"%>
  </div>
    <div class="small-12 medium-3 end columns">
    <%= f.label :tcelular, 'Telefone Celular' %><br>
    <%= f.text_field :tcelular, class: "fornecedor_tcelular" %>
  </div>


   <div class="small-12 medium-3 end columns">
    <%= f.label :email , 'E-mail' %><br>
    <%= f.text_field :email %>
  </div>

    <div class="small-12 medium-3 end columns">
    <%= f.label :site , 'Site' %><br>
    <%= f.text_field :site %>
  </div>

  </div>
  </fieldset>
  <div >
    <%= f.submit 'Salvar' , class: 'button' %>
  </div>
<% end %>

app/views/fornecedores/edit.html.erb
<h1 class="text-center">Edita fornecedor</h1>

<%= render 'form' %>

app/views/fornecedores/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Fornecedores</h1>

<table>
  <thead>
    <tr>
      <th>Nome fantasia</th>
      <th>Razão social</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedores.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.nomefantasia %></td>
        <td><%= fornecedor.razaosocial %></td>
        <td><%= link_to 'Exibir', fornecedor %></td>
        <td><%= link_to 'Editar', edit_fornecedor_path(fornecedor) %></td>
        <td><%= link_to 'Excluir', fornecedor, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= button_to 'Novo fornecedor', new_fornecedor_path, class: 'button', method: :get %>

app/views/fornecedores/new.html.erb
<h1 class="text-center">Novo Fornecedor</h1>

<%= render 'form' %>

app/views/fornecedores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nomefantasia:</strong>
  <%= @fornecedor.nomefantasia %>
</p>

<p>
  <strong>Razaosocial:</strong>
  <%= @fornecedor.razaosocial %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @fornecedor.endereco %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @fornecedor.bairro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @fornecedor.cep %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @fornecedor.estado_id %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @fornecedor.cidade_id %>
</p>

<p>
  <strong>Tcomercial:</strong>
  <%= @fornecedor.tcomercial %>
</p>

<p>
  <strong>Tcelular:</strong>
  <%= @fornecedor.tcelular %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @fornecedor.cnpj %>
</p>

<p>
  <strong>Ie:</strong>
  <%= @fornecedor.ie %>
</p>

<p>
  <strong>Email:</strong>
  <%= @fornecedor.email %>
</p>

<p>
  <strong>Im:</strong>
  <%= @fornecedor.im %>
</p>

<p>
  <strong>Site:</strong>
  <%= @fornecedor.site %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @fornecedor.categoria_id %>
</p>

<%= link_to 'Edit', edit_fornecedor_path(@fornecedor) %> |
<%= link_to 'Back', fornecedores_path %>