config/routes.rb
Rails.application.routes.draw do
  resources :eventos, path_names: { new: 'novo', edit: 'editar'}
  resources :contas_a_receber, path_names: { new: 'nova', edit: 'editar'}
  resources :contas_a_pagar, path_names: { new: 'nova', edit: 'editar'}
  resources :temas, path_names: { new: 'novo', edit: 'editar'}
  resources :fornecedores, path_names: { new: 'novo', edit: 'editar'}
  resources :categorias, path_names: { new: 'nova', edit: 'editar'}
  resources :clientes, path_names: { new: 'novo', edit: 'editar'}

  get 'estados/:id/cidades' => 'estados#cidades', as: :cidades_do_estado

  get 'contas_a_receber/evento/:id' => 'contas_a_receber#evento', as: :contas_a_receber_do_evento

  root 'eventos#index'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :fornecedores
end

app/models/categoria_fornecedor.rb
class CategoriaFornecedor < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :estado
  belongs_to :cidade

  has_many :eventos, dependent: :destroy
  has_many :contas_a_receber

  validates :nome, :estado, :cidade, presence: :true

end

app/models/conta_a_pagar.rb
class ContaAPagar < ActiveRecord::Base
  belongs_to :fornecedor
end

app/models/conta_a_receber.rb
class ContaAReceber < ActiveRecord::Base
  belongs_to :cliente

  validates :cliente, :vencimento, :valor, presence: :true
end

app/models/conta_pagar.rb
class ContaPagar < ActiveRecord::Base
end

app/models/conta_receber.rb
class ContaReceber < ActiveRecord::Base
end

app/models/dependente_cliente.rb
class DependenteCliente < ActiveRecord::Base
belongs_to :clientes
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :tema
  belongs_to :cliente
  belongs_to :tema

  validates :inicio, :fim, :cliente, :tema, presence: :true

  def valor_a_pagar
    self.entrada - self.desconto
  end
end

def print_strftime_formats(a,cur_date)
    a.each do |format|
        b = "%#{format}"
        output = cur_date.strftime(b)
        puts "t.strftime('#{b}'), => #{output}"
    end
end

a = ('a'..'z').to_a
A = ('A'..'Z').to_a

cur_date = Time.now

app/models/forma_pagamento.rb
class FormaPagamento < ActiveRecord::Base
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  belongs_to :estado
  belongs_to :cidade
  belongs_to :categoria
  has_many :contas_a_pagar
end

app/models/tema.rb
class Tema < ActiveRecord::Base
  has_many :eventos
end

app/controllers/contas_a_pagar_controller.rb
class ContasAPagarController < ApplicationController
  before_action :set_conta_a_pagar, only: [:show, :edit, :update, :destroy]

  # GET /contas_a_pagar
  # GET /contas_a_pagar.json
  def index
    @contas_a_pagar = ContaAPagar.all
  end

  # GET /contas_a_pagar/1
  # GET /contas_a_pagar/1.json
  def show
  end

  # GET /contas_a_pagar/new
  def new
    @conta_a_pagar = ContaAPagar.new
  end

  # GET /contas_a_pagar/1/edit
  def edit
  end

  # POST /contas_a_pagar
  # POST /contas_a_pagar.json
  def create
    @conta_a_pagar = ContaAPagar.new(conta_a_pagar_params)

    respond_to do |format|
      if @conta_a_pagar.save
        format.html { redirect_to @conta_a_pagar, notice: 'Conta a pagar was successfully created.' }
        format.json { render :show, status: :created, location: @conta_a_pagar }
      else
        format.html { render :new }
        format.json { render json: @conta_a_pagar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contas_a_pagar/1
  # PATCH/PUT /contas_a_pagar/1.json
  def update
    respond_to do |format|
      if @conta_a_pagar.update(conta_a_pagar_params)
        format.html { redirect_to @conta_a_pagar, notice: 'Conta a pagar was successfully updated.' }
        format.json { render :show, status: :ok, location: @conta_a_pagar }
      else
        format.html { render :edit }
        format.json { render json: @conta_a_pagar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contas_a_pagar/1
  # DELETE /contas_a_pagar/1.json
  def destroy
    @conta_a_pagar.destroy
    respond_to do |format|
      format.html { redirect_to contas_a_pagar_url, notice: 'Conta a pagar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conta_a_pagar
      @conta_a_pagar = ContaAPagar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conta_a_pagar_params
      params.require(:conta_a_pagar).permit(:fornecedor_id, :vencimento, :valor)
    end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  def cidades
    @cidades = Estado.find_by(id: params[:id]).cidades
  end
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_action :set_tema, only: [:show, :edit, :update, :destroy]

  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
  end

  # GET /temas/new
  def new
    @tema = Tema.new
  end

  # GET /temas/1/edit
  def edit
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(tema_params)

    respond_to do |format|
      if @tema.save
        format.html { redirect_to @tema, notice: 'Tema was successfully created.' }
        format.json { render :show, status: :created, location: @tema }
      else
        format.html { render :new }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temas/1
  # PATCH/PUT /temas/1.json
  def update
    respond_to do |format|
      if @tema.update(tema_params)
        format.html { redirect_to @tema, notice: 'Tema was successfully updated.' }
        format.json { render :show, status: :ok, location: @tema }
      else
        format.html { render :edit }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy
    @tema.destroy
    respond_to do |format|
      format.html { redirect_to temas_url, notice: 'Tema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tema
      @tema = Tema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tema_params
      params.require(:tema).permit(:nome, :obs)
    end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/conta_pagars_helper.rb
module ContaPagarsHelper
end

app/helpers/conta_recebers_helper.rb
module ContaRecebersHelper
end

app/helpers/contas_a_pagar_helper.rb
module ContasAPagarHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/contas_a_pagar/_form.html.erb
<%= form_for(@conta_a_pagar) do |f| %>
  <% if @conta_a_pagar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conta_a_pagar.errors.count, "error") %> prohibited this conta_a_pagar from being saved:</h2>

      <ul>
      <% @conta_a_pagar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Identificação</legend>
      <div class="row">
        <div class="small-12 medium-6 columns">
    <%= f.label :fornecedor_id, 'Selecionar Fornecedor'  %><br>
    <%= f.number_field :fornecedor_id %>
  </div>
  </div>


  <div class="row">
  <div class="small-12 medium-6 columns">
    <%= f.label :vencimento , 'Vencimento' %>
    <%= f.text_field :vencimento %>
  </div>
  </div>

   <div class="row">
  <div class="small-12 medium-6 columns">
    <%= f.label :valor, 'Valor' %><br>
    <%= f.text_field :valor, class: "contas_a_pagar_valor" %>
  </div>
  </div>

</fieldset>

   <div>
    <%= f.submit 'Salvar' , class: 'button' %>
  </div>
<% end %>

app/views/contas_a_pagar/edit.html.erb
<h1 class="text-center">Edita conta a pagar</h1>

<%= render 'form' %>

app/views/contas_a_pagar/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Contas a pagar</h1>

<table>
  <thead>
    <tr>
      <th>Fornecedor</th>
      <th>Vencimento</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contas_a_pagar.each do |conta_a_pagar| %>
      <tr>
        <td><%= conta_a_pagar.fornecedor_id %></td>
        <td><%= conta_a_pagar.vencimento %></td>
        <td><%= conta_a_pagar.valor %></td>
        <td><%= link_to 'Exibir', conta_a_pagar %></td>
        <td><%= link_to 'Editar', edit_conta_a_pagar_path(conta_a_pagar) %></td>
        <td><%= link_to 'Excluir', conta_a_pagar, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Nova conta a pagar', new_conta_a_pagar_path, class: 'button', method: :get %>

app/views/contas_a_pagar/new.html.erb
<h1 class="text-center">Nova Conta à Pagar</h1>

<%= render 'form' %>

app/views/contas_a_pagar/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fornecedor:</strong>
  <%= @conta_a_pagar.fornecedor_id %>
</p>

<p>
  <strong>Vencimento:</strong>
  <%= @conta_a_pagar.vencimento %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @conta_a_pagar.valor %>
</p>

<%= link_to 'Edit', edit_conta_a_pagar_path(@conta_a_pagar) %> |
<%= link_to 'Back', contas_a_pagar_path %>